apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jenkins.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jenkins.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jenkins.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      #serviceAccountName: {{ include "jenkins.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: "init"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "sh", "/var/jenkins_config/apply_config.sh" ]
          volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
          - name: jenkins-config
            mountPath: /var/jenkins_config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [ "--httpPort={{.Values.service.port}}"]
          ports:
            - name: http
              protocol: TCP
            - name: jnlp-port
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
          - name: plugins
            mountPath: /usr/share/jenkins/ref/plugins
          - name: plugin-dir
            mountPath: /var/jenkins_plugins
          - mountPath: /var/run/docker.sock
            name: docker-sock-volume
      volumes:
      - name: jenkins-home
        emptyDir: {}
      - name: docker-sock-volume
        hostPath:
          path: /var/run/docker.sock
          type: File
      - name: plugin-dir
        emptyDir: {}
      - name: plugins
        emptyDir: {}
      - configMap:
          defaultMode: 420
          name: {{ include "jenkins.fullname" . }}-config
        name: jenkins-config 
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
