apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (eq .Values.service.type "NodePort") }}
      nodePort: {{.Values.service.nodePort}}
      {{- end }}
  selector:
    {{- include "jenkins.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    {{- include "jenkins.selectorLabels" . | nindent 4 }}